server:
  port: ${API_GATEWAY_PORT}

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**
        - id: trip-service
          uri: ${TRIP_SERVICE_URL}
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - JwtAuthFilter
        - id: billing-service
          uri: ${BILLING_SERVICE_URL}
          predicates:
            - Path=/api/v1/billing/**
          filters:
            - JwtAuthFilter
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL}
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - JwtAuthFilter
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            key-resolver: "#{@ipKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}

eureka:
  client:
    enabled: false
